Dashlane/passkeys-resources

resources/compatible-domains.json
This is a demo site run by Corbado
=> [NEW] passkeys.eu

resources/compatible-domains.json
-   **Domain Name**: carnival.com
-   **Purpose**:  deals and cruise packages
-   **Relevance**: 
-   **Additional Information**: n/a
=> [NEW] carnival.com

resources/compatible-domains.json
-   **Domain Name**:  hyatt.com
-   **Purpose**: Hotels
-   **Relevance**: <img width="1504" alt="Screenshot 2023-07-05 at 12 05 51" src="https://github.com/Dashlane/passkeys-resources/assets/8578329/45511be5-2075-43a8-8a98-608fc6cfc70e">
=> [NEW] hyatt.com

resources/compatible-domains.json
-   **Domain Name**: kenwoodworld.com
-   **Purpose**: Consumer goods
-   **Relevance**: 
-   **Additional Information**: Same backend as carnival.com (ownid)
=> [New] kenwoodworld.com

resources/compatible-domains.json
=> [NEW] ivoclar.com

resources/compatible-domains.json
magic.link
web3 wallet
Need a premium account to test, but seems you can have passwordless login via webauthn
=> [NEW] magic.link

resources/compatible-domains.json
offshoot.rentals
Video production
=> [NEW] offshoot.rentals

resources/compatible-domains.json
[onlyfans.com](https://onlyfans.com/)
Social Network
=> [NEW] onlyfans.com

resources/compatible-domains.json
Amazon.com and potentially all amazon domains but cannot check them all.
Retail
This is being rolled out so not all users may experience passkeys
=> [NEW] amazon.com

resources/compatible-domains.json
nintendo.com
gaming
https://en-americas-support.nintendo.com/app/answers/detail/a_id/62531
=> [NEW] nintendo.com

resources/compatible-domains.json
uber.com
Ride hailing/food delivery
https://twitter.com/timcappalli/status/1706456237326381344
=> [NEW] uber.com

resources/compatible-domains.json
coinbase.com
Crypto currency
https://help.coinbase.com/en/coinbase/getting-started/getting-started-with-coinbase/passkeys
=> [NEW] coinbase.com

resources/compatible-domains.json
apple.com
Get you to buy stuff
Seems available on all their login screens
=> [New] apple.com

website/tools/fetch-domains.js
This PR allows to fallback on `www` when the domain has no redirect.
It improves the compatibility with some exotic websites syntax.
=> Improve domain fetch (www fallback)

resources/compatible-domains.json, website/tools/fetch-domains.js
Redirects with leading `/` were not processed properly by axios.
Also websites blocking automated scripts were not referred.
=> Improve fetching domains with redirect

website/tools/fetch-domains.js
Error management on fetching broke pipeline.
=> Improve fetching domains error management

resources/compatible-domains.json
linkedin.com
Professional social network
https://www.linkedin.com/help/linkedin/answer/a4500181?lang=en-US
Does not seem widely available yet, but probably a matter of time
=> [NEW] linkedin.com

resources/compatible-domains.json
crowdin.com
Localisation
https://accounts.crowdin.com/login
=> [NEW] crowdin.com

resources/compatible-domains.json
tender.run
Finance
https://tender.run/passkeys#what-is-a-passkey
=> [NEW] tender.run

resources/compatible-domains.json
discord.com
chat
https://discord.com/blog/how-discord-modernized-mfa-with-webauthn
=> [NEW] discord.com

resources/compatible-domains.json
moneybird.com
Accounting
https://moneybird.com/login
=> [NEW] moneybird.com

resources/compatible-domains.json
=> [NEW] fleeps.co

resources/compatible-domains.json
twitter.com
x.com
No useful purpose
https://help.twitter.com/en/managing-your-account/how-to-use-passkey
=> [New] Twitter.com

resources/compatible-domains.json
target.com
Retail
https://www.target.com/login
=> [NEW] target.com

resources/compatible-domains.json
roblox.com
Gaming
https://en.help.roblox.com/hc/en-us/articles/20669991483156-Logging-in-with-a-Passkey
=> [NEW] roblox.com

resources/compatible-domains.json
finom.co
Banking
https://finom.co/en-fr/blog/passkeys-finom/
=> [NEW] finom.co

.github/workflows/validate-json.yml, resources/compatible-domains.json
Avoid incorrect JSON submission by validating format and ordering.
=> Validate JSON format workflow

resources/compatible-domains.json
bookmyname.com
BookMyName is a domain name registrar
=> add bookmyname.com

resources/compatible-domains.json
nfl.com
sports
https://support.nfl.com/hc/en-us/articles/13594192451740-Using-biometric-authentication-as-an-alternative-to-a-password-i-e-Use-Touch-ID-Face-ID-etc
=> [NEW] nfl.com

resources/compatible-domains.json
affirm.com
Payments
https://helpcenter.affirm.com/s/article/Set-up-a-Passkey
=> [NEW] affirm.com

resources/compatible-domains.json
hubspot.com
CRM
https://www.linkedin.com/posts/jordan-aron-46056020_passkeysweek-passkeys-fido-activity-7264636444852314113-sDpc?utm_source=share&utm_medium=member_desktop
=> [NEW] hubspot.com

resources/compatible-domains.json
=> [NEW] hcaptcha.com

resources/compatible-domains.json
wellsfargo.com
Finance
https://www.wellsfargo.com/help/security-and-fraud/passkey-faqs/
=> [NEW] wellsfargo.com

resources/compatible-domains.json
=> [NEW] bolt.eu

resources/compatible-domains.json
intuit.com
Book keeping
https://quickbooks.intuit.com/learn-support/en-us/help-article/multi-factor-authentication/use-passkeys-sign-intuit-account/L1CoQYJWE_US_en_US
=> [NEW] intuit.com
